version: '3.8'

services:
  go:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_go
    volumes:
      - ./bin:/build/bin
    networks:
      - site_form_checker

  chrome:
    image: chromedp/headless-shell:latest
    container_name: ${APP_NAME}_chrome
    user: nobody
    shm_size: 2G
    expose:
      - "9222/tcp"
    ports:
      - "127.0.0.1:9222:9222"
    networks:
      - site_form_checker

  mariadb:
    image: mariadb:11.1.2
    container_name: ${APP_NAME}_mariadb
    expose:
      - "3306/tcp"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=${DB_NAME}
    depends_on:
      - phpmyadmin
    networks:
      - site_form_checker

  phpmyadmin:
    image: phpmyadmin:5
    container_name: ${APP_NAME}_phpmyadmin
    restart: always
    expose:
      - "80/tcp"
    ports:
      - "8092:80"
    environment:
      - PMA_HOST=mariadb
    networks:
      - site_form_checker

networks:
  site_form_checker:
    name: site_form_checker
    driver: bridge