version: '3.8'

services:
  go:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_go
    volumes:
      - ./bin:/build/bin
    networks:
      - site_form_checker

  chrome:
    image: browserless/chrome:latest
    container_name: ${APP_NAME}_chrome
    expose:
      - "3000"
    ports:
      - "127.0.0.1:9222:3000"
    networks:
      - site_form_checker

networks:
  site_form_checker:
    name: site_form_checker
    driver: bridge