version: '3.8'

services:
  go:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_go
    volumes:
      - ./bin:/build/bin
    networks:
      - site_form_checker

  chrome:
    image: chromedp/headless-shell:latest
    container_name: ${APP_NAME}_chrome
    user: nobody
    shm_size: 2G
    expose:
      - "9222/tcp"
    ports:
      - "127.0.0.1:9222:9222"
    networks:
      - site_form_checker

networks:
  site_form_checker:
    name: site_form_checker
    driver: bridge